version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@quasar/extras"
    versions:
    - 1.10.0
    - 1.10.2
    - 1.10.3
    - 1.9.14
    - 1.9.15
    - 1.9.16
    - 1.9.17
    - 1.9.18
    - 1.9.19
    - 1.9.20
  - dependency-name: vue-i18n
    versions:
    - 8.22.4
    - 8.23.0
    - 8.24.0
    - 8.24.1
    - 8.24.2
    - 8.24.3
  - dependency-name: "@quasar/app"
    versions:
    - 2.1.14
    - 2.1.15
    - 2.2.1
    - 2.2.3
    - 2.2.4
  - dependency-name: quasar
    versions:
    - 1.15.1
    - 1.15.10
    - 1.15.2
    - 1.15.3
    - 1.15.4
    - 1.15.5
    - 1.15.7
    - 1.15.9
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
